[package]
authors = ["Jason Ozias <jason.ozias@kroger.com>"]
description = "An implementation of Shamir's Secret Sharing Scheme"
documentation = "http://docs.rs/ssss"
edition = "2018"
homepage = "http://docs.rs/ssss"
keywords = ["cryptography","secret","shamir"]
license = "MIT/Apache-2.0"
name = "ssss"
readme = "README.md"
repository = "https://github.com/rustyhorde/sss.git"
version = "0.1.0"

[dependencies]
getset = "0"
rand = "0"
serde = "1"
serde_derive = "1"
